"""Report PDF Generation Utility"""

from reportlab.lib.pagesizes import letter, A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak
from datetime import datetime
from io import BytesIO
from typing import List, Dict, Any


class ReportGenerator:
    """Generate PDF reports for attendance data"""

    def __init__(self, title: str, generated_by: str = "Admin"):
        self.title = title
        self.generated_by = generated_by
        self.generated_date = datetime.now().strftime("%B %d, %Y at %I:%M %p")
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()

    def _setup_custom_styles(self):
        """Setup custom paragraph styles"""
        self.title_style = ParagraphStyle(
            'CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=18,
            textColor=colors.HexColor('#1a237e'),
            spaceAfter=12,
            alignment=1,  # Center
            fontName='Helvetica-Bold'
        )

        self.subtitle_style = ParagraphStyle(
            'CustomSubtitle',
            parent=self.styles['Normal'],
            fontSize=10,
            textColor=colors.HexColor('#424242'),
            spaceAfter=4,
            alignment=1,  # Center
        )

        self.heading_style = ParagraphStyle(
            'CustomHeading',
            parent=self.styles['Heading2'],
            fontSize=14,
            textColor=colors.HexColor('#1a237e'),
            spaceAfter=8,
            fontName='Helvetica-Bold'
        )

    def _get_header_table(self) -> Table:
        """Create header table with title and date info"""
        data = [
            [Paragraph(self.title, self.title_style)],
            [Paragraph(f"Generated on: {self.generated_date}", self.subtitle_style)],
            [Paragraph(f"Generated by: {self.generated_by}", self.subtitle_style)],
        ]

        table = Table(data, colWidths=[7.5 * inch])
        table.setStyle(TableStyle([
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ]))

        return table

    def _get_metadata_table(self, filters: Dict[str, Any]) -> Table:
        """Create metadata table showing applied filters"""
        metadata = []
        for key, value in filters.items():
            if value:
                display_key = key.replace('_', ' ').title()
                display_value = str(value) if value is not None else "N/A"
                metadata.append([display_key, display_value])

        if not metadata:
            return None

        table = Table(metadata, colWidths=[2 * inch, 5.5 * inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#e8eaf6')),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f5f5f5')]),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#c0c0c0')),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ]))

        return table

    def _get_data_table(self, headers: List[str], data: List[List[Any]]) -> Table:
        """Create data table with headers and rows"""
        if not data:
            return None

        # Combine headers and data
        table_data = [headers] + data

        # Calculate column widths - give more space to subject name column
        num_cols = len(headers)
        if num_cols >= 6:  # Student report has 6 columns
            col_widths = [
                1.0 * inch,  # Subject Code
                2.5 * inch,  # Subject Name (wider for wrapping)
                1.2 * inch,  # Faculty
                1.0 * inch,  # Total Lectures
                0.9 * inch,  # Attended
                1.0 * inch   # Attendance %
            ]
        elif num_cols == 5 and headers[0] == 'Sr. No.':  # Faculty report has 6 columns
            col_widths = [
                0.5 * inch,  # Sr. No.
                2.0 * inch,  # Enrollment No.
                2.0 * inch,  # Student Name (wider for wrapping)
                #1.4 * inch,  # Total Lectures
                1.4 * inch,  # Lectures Attended
                1.0 * inch   # Attendance %
            ]
        else:
            col_width = 7.5 * inch / num_cols
            col_widths = [col_width] * num_cols

        table = Table(table_data, colWidths=col_widths, repeatRows=1)

        # Style the table
        table_style = [
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1a237e')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, 0), 'CENTER'),  # Header alignment
            ('ALIGN', (0, 1), (-1, -1), 'CENTER'),  # Default data alignment
            ('ALIGN', (1, 1), (1, -1), 'LEFT'),     # Subject Name column (student report) left-aligned for wrapping
            ('ALIGN', (2, 1), (2, -1), 'LEFT'),     # Student Name column (faculty report) left-aligned for wrapping
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 9),      # Reduced header font size
            ('FONTSIZE', (0, 1), (-1, -1), 10),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f5f5f5')]),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#cccccc')),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('LEFTPADDING', (0, 0), (-1, -1), 4),
            ('RIGHTPADDING', (0, 0), (-1, -1), 4),
            # Allow text wrapping in subject name column and headers
            ('WORDWRAP', (0, 0), (-1, 0), True),   # Enable word wrap for headers
            ('WORDWRAP', (1, 0), (1, -1), True),   # Enable word wrap for subject name column (student report)
            ('WORDWRAP', (2, 0), (2, -1), True),   # Enable word wrap for student name column (faculty report)
        ]

        # Add conditional coloring for attendance percentage column in faculty reports
        if num_cols == 5 and headers[0] == 'Sr. No.':  # Faculty report
            pct_col = num_cols - 1  # Last column is attendance %
            for row_idx, row_data in enumerate(data, 1):  # Start from 1 to skip header
                attendance_pct = 0
                if len(row_data) > pct_col:
                    pct_str = str(row_data[pct_col]).replace('%', '')
                    try:
                        attendance_pct = float(pct_str)
                    except (ValueError, TypeError):
                        attendance_pct = 0

                # Green for >= 75%, Red for < 75%
                color = colors.green if attendance_pct >= 75 else colors.red
                table_style.append(('BACKGROUND', (pct_col, row_idx), (pct_col, row_idx), color))
                table_style.append(('TEXTCOLOR', (pct_col, row_idx), (pct_col, row_idx), colors.white))

        table.setStyle(TableStyle(table_style))
        return table

    def generate_pdf(
        self,
        headers: List[str],
        data: List[List[Any]],
        filters: Dict[str, Any] = None,
        filename: str = "report.pdf"
    ) -> bytes:
        """
        Generate PDF report and return bytes

        Args:
            headers: Column headers for data table
            data: Rows of data
            filters: Applied filters to display in metadata section
            filename: Output filename

        Returns:
            PDF bytes
        """
        buffer = BytesIO()

        # Create PDF document
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=0.5 * inch,
            leftMargin=0.5 * inch,
            topMargin=0.5 * inch,
            bottomMargin=0.5 * inch,
        )

        # Build story
        story = []

        # Add header
        story.append(self._get_header_table())
        story.append(Spacer(1, 0.3 * inch))

        # Add filters if provided
        if filters:
            filters_table = self._get_metadata_table(filters)
            if filters_table:
                story.append(Paragraph("Report Filters", self.heading_style))
                story.append(filters_table)
                story.append(Spacer(1, 0.3 * inch))

        # Add data table
        data_table = self._get_data_table(headers, data)
        if data_table:
            story.append(data_table)

        # Build PDF
        doc.build(story)

        # Get PDF bytes
        buffer.seek(0)
        return buffer.getvalue()

    @staticmethod
    def generate_department_report(
        report_title: str,
        departments: List[str],
        years: List[int],
        subjects: List[str],
        attendance_data: List[Dict[str, Any]],
        filters: Dict[str, Any],
        generated_by: str
    ) -> bytes:
        """Generate department-level report"""
        generator = ReportGenerator(report_title, generated_by)

        headers = ["Department", "Year", "Subject", "Total Students", "Present", "Absent", "Attendance %"]
        data = []

        for record in attendance_data:
            row = [
                record.get("department", ""),
                record.get("year", ""),
                record.get("subject", ""),
                record.get("total_students", 0),
                record.get("present", 0),
                record.get("absent", 0),
                f"{record.get('attendance_percentage', 0):.2f}%"
            ]
            data.append(row)

        return generator.generate_pdf(headers, data, filters)

    @staticmethod
    def generate_student_report(
        report_title: str,
        student_name: str,
        attendance_data: List[Dict[str, Any]],
        filters: Dict[str, Any],
        generated_by: str
    ) -> bytes:
        """Generate student-level report"""
        generator = ReportGenerator(report_title, generated_by)

        headers = ["Subject Code", "Subject Name", "Faculty", "Total Lectures", "Attended", "Attendance %"]
        data = []

        total_attended = 0
        total_lectures = 0

        for record in attendance_data:
            total_lectures_subject = record.get("total_lectures", 0)
            attended_subject = record.get("attended", 0)
            attendance_pct = (attended_subject / total_lectures_subject * 100) if total_lectures_subject > 0 else 0

            # Use Paragraph for subject name to allow text wrapping
            subject_name = record.get("subject_name", "")
            subject_name_para = Paragraph(subject_name, generator.styles['Normal']) if subject_name else ""

            row = [
                record.get("subject_code", ""),
                subject_name_para,  # Use Paragraph for wrapping
                record.get("faculty", ""),
                total_lectures_subject,
                attended_subject,
                f"{attendance_pct:.2f}%"
            ]
            data.append(row)

            total_attended += attended_subject
            total_lectures += total_lectures_subject

        # Add summary row
        overall_pct = (total_attended / total_lectures * 100) if total_lectures > 0 else 0
        data.append([
            "OVERALL",
            Paragraph("All Subjects", generator.styles['Normal']),  # Use Paragraph for consistency
            "",
            total_lectures,
            total_attended,
            f"{overall_pct:.2f}%"
        ])

        return generator.generate_pdf(headers, data, filters)

    @staticmethod
    def generate_faculty_report(
        report_title: str,
        faculty_name: str,
        attendance_data: List[Dict[str, Any]],
        filters: Dict[str, Any],
        generated_by: str
    ) -> bytes:
        """Generate faculty-level report"""
        generator = ReportGenerator(report_title, generated_by)

        headers = ["Sr. No.", "Enrollment No.", "Student Name", "Lectures Attended", "Attendance %"]
        data = []

        for record in attendance_data:
            # Use Paragraph for student name to allow text wrapping
            student_name = record.get("student_name", "")
            student_name_para = Paragraph(student_name, generator.styles['Normal']) if student_name else ""

            row = [
                record.get("sr_no", ""),
                record.get("enrollment_number", ""),
                student_name_para,  # Use Paragraph for wrapping
                #record.get("total_lectures", 0),
                record.get("lectures_attended", 0),
                f"{record.get('attendance_percentage', 0):.2f}%"
            ]
            data.append(row)

        return generator.generate_pdf(headers, data, filters)
